Device:
    Configuration:
        Device: 2410
        #use 'COM<n>' for Windows (n is integer)
        #use '/dev/ttyUSB<n>' for Linux/MAC (n is integer)
        Port: '/dev/tty.usbserial-FTXG6Y8TD'
        Baudrate: 19200
        TimeOut: 2
        
        Measure: 'A'
        # For ComplianceMeasure
        # For 2400 Series:
        #     current: from -1.05A to +1.05A
        #     voltage: from -210V to +210V
        # For 2410 Series:
        #     current: from -1.05A to +1.05A
        #     voltage: from -1100V to +1100V
        ComplianceMeasure: 0.000105
        RangeMeasure: 1.8
        
        Source: 'V'   
        #For ComplianceSoucre
        #If Source is 'V' -> from 20 to 160 in 20V steps
        ComplianceSource: 40
        # For RangeSource
        # For 2400 Series:
        #     current: from -1.05A to +1.05A
        #     voltage: from -210V to +210V
        # For 2410 Series:
        #     current: from -1.05A to +1.05A
        #     voltage: from -1100V to +1100V
        RangeSource:  1.8
        
        TriggerCount: 15
        TriggerDelay: 0.001
        #not less than 0.05s for reading hole dataset (from the keithley to the pc)
        WaitRead: 0.08  
        #time between setting the source and measuring
        SettlingTime: 0.1
        AutoRangeMeasure: 'ON'
        AutoRangeSource: 'ON'

        SettlingTime: 0.1
    Sweep:
        LowValue: 0.0
        HighValue: 1.8
        Points: 90
        Points_down: 3    #Number of points for ramping down